### ISSUE TITLE
Game Steam Freezing

### ISSUE THREAD

**Issue by drakenabarion** [mariotaku/moonlight-tv#135] opened 2022-01-16 18:06 UTC
While playing the game on an RTX3080 to an LG CX, the video stream randomly freezes. Audio continues.

Settings include:
3280x2160 60FPS
60,000 allowed data transfer
SMP + HDR

Log file attached from
C:\ProgramData\NVIDIA Corporation\NvStream

I cant tell if this is a driver issue or something else. It happens mostly in God of War. Does not happen with Horizon Zero Dawn or Death Stranding, however.

[NvStreamerCurrent.log](https://github.com/mariotaku/moonlight-tv/files/7877605/NvStreamerCurrent.log)

**Comment by mariotaku** [comment] 2022-01-17 04:04
Hello. Have you tried lower bitrate? webOS can't smoothly stream if bitrate too high sometimes.

**Comment by drakenabarion** [comment] 2022-01-17 19:07
> Hello. Have you tried lower bitrate? webOS can't smoothly stream if bitrate too high sometimes.

Thank you for the reply. I lowered the Bitrate to 35,000k, which is the highest in the settings that does not give a warning about high bit rates.

In the last minutes of gameplay, I was getting freezing within 10-20 seconds of restarting the stream. (I would hold back on the remote, then yellow button to disconnect, then reconnect).

Here are the last two logs, if that helps.
[NvStreamerCurrent 17-Jan-2022 9.01pm.log](https://github.com/mariotaku/moonlight-tv/files/7884191/NvStreamerCurrent.17-Jan-2022.9.01pm.log)
[NvStreamerOld 17-Jan-2022 9.01pm.log](https://github.com/mariotaku/moonlight-tv/files/7884192/NvStreamerOld.17-Jan-2022.9.01pm.log)

**Comment by mariotaku** [comment] 2022-01-18 16:34
Hmm. Does NDL work for you?

**Comment by drakenabarion** [comment] 2022-01-18 16:55
> Hmm. Does NDL work for you?

Its the same behaviour with the freezing. Other than the colours being different it performs more or less the same, but maybe lower latency.

**Comment by mariotaku** [comment] 2022-01-18 17:08
Since you're on 3080 I don't think it's caused by performance issue. Does it happen on other clients?

**Comment by drakenabarion** [comment] 2022-01-18 17:54
I just tried Moonlight on a MiBox 4S, and it also has the issue there. So that likely rules out the WebOS version as the cause, and I guess its my PC.

<pondering emoji that I dont know how to add to this text>

**Comment by mariotaku** [comment] 2022-01-19 01:03
Got it. I'll close this issue, and if you find proper solution, feel free to post here.

**Closed by mariotaku** 2022-01-19 01:03 UTC

**Comment by drakenabarion** [comment] 2022-01-19 23:08
Disabling Hardware GPU Scheduling seems up have stopped freezing. I do see a stutter sometimes which I suspect would have otherwise have froze.
