### ISSUE TITLE
[BUG] Moonlight crashes when opening a game

### ISSUE THREAD

**Issue by Philipou** [mariotaku/moonlight-tv#201] opened 2023-01-21 16:29 UTC
**Describe the bug**

Everytime i click on a game in moolight on my TV, it says it's connecting and then the TV app instantly crashes. (it still opens the game on my computer)

**To Reproduce**

1. Go to Moonlight
2. Click on a computer in the list
3. Click on a game

**Expected behavior**

Moonlight should stream the game from my computer to my TV

**Basic information**

 - Moonlight version: 1.5.3
 - Model: 43UM7050PLF
 - webOS version WebOS version: 05.30.20 ( WebOS Tv version : 4.9.7-13 [goldilocks2-gyoen])

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version

**Additional context**

Default settings in Moonlight, app instantly crashes without any error report.

**Comment by mariotaku** [comment] 2023-01-22 06:39
Might be a duplicate of #184

**Closed by mariotaku** 2023-01-22 06:40 UTC
