### ISSUE TITLE
[COMPAT] No Video on 32LK6200PLA

### ISSUE THREAD

**Issue by banan4phon3** [mariotaku/moonlight-tv#164] opened 2022-07-22 17:04 UTC
## Basic information

 - Device model: ( 32LK6200PLA) 
 - Firmware version: ( 05.40.26) 
 - webOS version: (4.4.0-12(goldilocks-gorce)) 
 - Moonlight version: ( 1.4.7) 
 - Is audio working: ( Yes ) 
 - Is video working: (Yes) 
 - Is input working: ( Yes) 

## Description
 After starting a game and the loading of the stream, the stream instantly freezes at the first frame and after around 10 seconds "unstable connection" sign shows up, sound and input to the game still work. I tried putting bitrate, resolution and fps as far down as possible. Tv has internet connection through cabel.

**Comment by mariotaku** [comment] 2022-07-22 17:17
This sounds like #35 .

**Comment by banan4phon3** [comment] 2022-07-23 08:57
I tried the version 0.6.6 in hope it would work with it but didn't help, is there something elxe I can try?

**Comment by mariotaku** [comment] 2022-07-23 09:31
It's fine to replace versions directly. But I'm afraid the issue is on the TV side. This certain series can't play video properly.

**Comment by banan4phon3** [comment] 2022-07-23 23:25
Damn that's a shame, is there any hope, that a future version could work with it?

**Comment by mariotaku** [comment] 2022-07-24 03:54
This will require someone who's both capable of making patches for moonlight and have such TV. I don't have access to this TV so it's impossible to see what's going on inside. Let's first close this issue and move discussions to #35 .

**Closed by mariotaku** 2022-07-24 03:54 UTC
Labels: compatibility, video

**Comment by 4tl4sh** [comment] 2023-01-21 16:38
Having similar issue but without the first frame.

Default settings works OK. Here's my testing (audio and control works OK in any configuration).

**Model:** 43UK6400PLF
**webOS:** 4.4.0


<html>
<body>


**Decoder / Codec** | **Working resolutions** 
-- | --
**SMP h264** | None 
**SMP h265** | None
**NDL h264** | 720, 1080, 1440* 
**NDL h265** | Not compatible
**NetCast Legacy** | 720, 1080, 1440*


</body>
</html>

*1440 streams but with a green glitch screen. Only 720 and 1080 resolutions work properly at 30 or 60 fps allowing multiple bitrate settings.
