### ISSUE TITLE
[BUG] 0.1.5

### ISSUE THREAD

**Issue by Nez-debug** [mariotaku/moonlight-tv#17] opened 2021-01-19 18:04 UTC
**Describe the bug**
If SDL is unchecked when leaving settings it closes moonlight and settings aren't saved.

**To Reproduce**
1. Go to Settings
2. Amend your settings.
3. Leave SDL unchecked
4. Click the X to exit.

**LG webOS TV (please complete the following information):**
 - Model: [43UH668V-ZA]
 - webOS version [3.3.4-4220]

**Comment by mariotaku** [comment] 2021-01-19 19:02
I missed an important step, which is closing the dialog, so I was not able to reproduce. Now it should be fixed in v0.1.7. If you think this has fixed, please let me know.

**Comment by mariotaku** [comment] 2021-01-20 03:56
Done. Fixed in 000efd0962ec51576bb3e70c39a497af33bbcac7.

**Closed by mariotaku** 2021-01-20 03:56 UTC
