### ISSUE TITLE
Moonlight app not launching on LG TV

### ISSUE THREAD

**Issue by Jakeasaur** [mariotaku/moonlight-tv#308] opened 2023-09-09 11:43 UTC
## Bug Description

I followed the installation guide provided for the installation of the Moonlight application to an LG TV using the webOS dev app on my pc. I connected the devices as required and installed the Moonlight app from the list of available options on the webOS app using my PC. On checking my TV, the Moonlight app appears to have installed correctly, showing in the list of available apps on the home menu. However, when trying to launch the app, the splash screen with the logo shows, but then the TV returns to whatever was open before. I cannot get into the Moonlight app itself on the TV, and I am unsure why. 

I have tried to research possible solutions but found nothing specific to this issue. I installed the desktop version of Moonlight on my PC and that seemed to be in working order, and likewise for my android mobile. Without any specific error messages I'm not sure how to proceed, or where I can find any possible crash report or log for the app on the TV from the webOS dev app on my PC.

## Reproduce Steps

1. Install latest version of WebOS dev manager app as per recommended installation instructions provided by Moonlight for LG TVs.
2.  Follow instructions provided in the webOS app to enable Dev mode on the LG TV and link to the webOS app on PC.
3. Install Moonlight on the LG TV using the webOS app.
4. Attempt launching Moonlight app on LG TV.

## Expected Behavior
I have been unable to attempt to proceed with the instructions following the launch of Moonlight on the TV because of this issue, so I do not yet know if there are any other potential barriers to using it to stream games from my PC to my TV.

---

## Basic Information

 - Moonlight Info in Settings - About: Unable to access due to this error.
 - Are you using GFE or Sunshine? If so, what's the version? N/A
 - The TV model is a 50UQ75006LF. I do not know if the TV is known to be compatible or not, which may be the issue.

## Additional Context
None available.

**Comment by mariotaku** [comment] 2023-09-09 11:50
This is a duplicate of #303. A new version will be out soon to fix this issue.

**Closed by mariotaku** 2023-09-09 11:50 UTC
Labels: bug

**Comment by Jakeasaur** [comment] 2023-09-09 11:52
Ah, apologies, thank you for clarifying.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
