### ISSUE TITLE
[BUG] Sunshine doesn't work with NDL but does with SMP

### ISSUE THREAD

**Issue by thehhmdb** [mariotaku/moonlight-tv#183] opened 2022-11-08 19:56 UTC
**Describe the bug**

When the host is running standard Gamestream (without Sunshine), both NDL and SMP work.
When the same host is running Sunshine, SMP works but NDL doesn't. NDL seems to display one frame as a still picture. Inputs are still working e.g. you can see a mouse pointer moving around on the host, but the client is frozen on that one frame.

**To Reproduce**

Install Sunshine from here on Windows:
https://github.com/LizardByte/Sunshine

Open the Client with NDL or Auto.

**Expected behavior**

NDL shows a moving video stream like SMP

**Basic information**

 - Moonlight version: 1.5.3
 - Model: CX48 and CX55
 - webOS version 5.4.1-10

Thanks

**Comment by caioavidal** [comment] 2023-03-02 21:17
That might be an issue on Sunshine side. I will check the network bytes later.
@thehhmdb What GPU are you using?

**Comment by thehhmdb** [comment] 2023-03-02 21:47
I've seen the same happen on a RTX 3080 and a RTX 4090.

I've also opened an issue on the Sunshine side as well with some more information:
https://github.com/LizardByte/Sunshine/issues/722

The latest I've noticed is:
Launching Moonlight with a static desktop = failure (stuck on one frame)
Launching Moonlight with a video playing = works (streams normally)

**Comment by RossDanbyGamer** [comment] 2023-03-12 15:53
To reiterate what I just posted in the issue above:

It Appears to be an audio related issue when using LG webOS NDL + NDL Audio (Decoder Provided). If the user selects a different audio decoder other than the one provided by the video decoder such as ALSA or PulseAudio, the stream has no issues starting.

When audio is already playing before connecting, the user may switch back to using NDL Audio without the frozen static image.

**Comment by RossDanbyGamer** [comment] 2023-03-12 16:00
> I've seen the same happen on a RTX 3080 and a RTX 4090.
> 
> I've also opened an issue on the Sunshine side as well with some more information: [LizardByte/Sunshine#722](https://github.com/LizardByte/Sunshine/issues/722)
> 
> The latest I've noticed is: Launching Moonlight with a static desktop = failure (stuck on one frame) Launching Moonlight with a video playing = works (streams normally)

@thehhmdb I suspect this is a decoder issue on the LG TVs. Another issue I noticed when using NDL is HDR being enabled on an SDR stream where in the clients settings HDR is disabled. SMP handles it correctly.

**Comment by mariotaku** [comment] 2023-06-19 06:10
v1.5.10 might fix this issue by prevent opening/closing NDL decoder too frequently.

**Comment by chocomega** [comment] 2023-06-19 15:27
For reference, I have this hacky workaround:
Launch a script to play a dummy sound ("Command Preparations" in Sunshine) to "unlock" the video decoder.
Interestingly, when the sound is played the TV displays all the previous frames in the buffer until now

**Comment by hugocowan** [comment] 2023-06-19 18:56
I too am seeing this issue with video output freezing on the first frame. Playing a sound on the host device fixes it as people are describing. Hope you can reproduce @mariotaku and would be happy to help if you need it.

**Comment by tomalek0** [comment] 2023-09-21 14:54
Moonlight version 1.5.20 with Sunshine, I hear the sound from the TV but after few secs of black screen I get "dedoder reported error" and it closes. Tried using NDL with all different audio decoders - same. Tried having a youtube video with sound - same. 
I can't test SMP since it instantly crashes my moonlight - can't even get to settings so I have to reinstall.
On the legacy decoder I get a green screen with sound and after a while "decoder reported error".

GFE works great.

**Comment by tomalek0** [comment] 2023-09-22 09:52
Update for version 1.5.23:
using SMP no longer crashes, but when connecting to Sunshine it's stuck on "Connecting..." and from sunshine logs:

[2023:09:22:11:48:30]: Info: SDR color coding [Rec. 709]
[2023:09:22:11:48:30]: Info: Color range: [JPEG]
[2023:09:22:11:48:30]: Info: 
[2023:09:22:11:48:30]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:09:22:11:48:30]: Info: 
[2023:09:22:11:48:30]: Info: Found encoder nvenc: [h264_nvenc, hevc_nvenc]
[2023:09:22:11:48:30]: Info: Spawning [steam steam://open/bigpicture] in ["C:\Program Files (x86)\Steam"]
[2023:09:22:11:48:45]: Info: steam steam://open/bigpicture running with PID 4344
[2023:09:22:11:48:45]: Info: Executing [Desktop]
[2023:09:22:11:48:45]: Info: CLIENT CONNECTED
[2023:09:22:11:48:55]: Error: Initial Ping Timeout

**Comment by mariotaku** [comment] 2023-10-05 02:25
@thehhmdb @chocomega @RossDanbyGamer Recent versions (v1.5.25 and up) plays an empty audio sample while opening stream. Does this fix NDL playback on webOS 5+?

**Comment by thehhmdb** [comment] 2023-10-05 17:48
> @thehhmdb @chocomega @RossDanbyGamer Recent versions (v1.5.25 and up) plays an empty audio sample while opening stream. Does this fix NDL playback on webOS 5+?

Yes, it seems to be working fine for me too. Thanks!

**Closed** 2023-10-11 16:15 UTC
Labels: bug, video
