### ISSUE TITLE
[BUG] video freeze after some time

### ISSUE THREAD

**Issue by Melonso** [mariotaku/moonlight-tv#112] opened 2021-10-16 20:15 UTC
Hello
I have oled 55B9 TV
5.10.30 webos
5GHz wifi
1440p video stream
when I play for about half an hour - an hour, the picture freezes but the sound goes on.  the only thing that helps is to exit the stream.  the first attempt to reconnect to the game crashes, connection time out (1).  the connection is successful the second time, but the situation repeats itself in a few - several minutes.

**Comment by mariotaku** [comment] 2021-10-17 02:45
Please provide information below:

* Moonlight version
* webOS version (**not to be confused with firmware version 05.10.30**)
* Decoder using right now (SMP, NDL etc)

> To check version, go to Settings > Quick Settings > General > About this TV > webOS TV Version


Also, did you try other decoders?

**Comment by cgutman** [comment] 2021-10-17 03:18
What is the Nvidia driver version on your host PC?

**Comment by Melonso** [comment] 2021-10-17 09:07
web os is 05.10.30
Nvidia drivers 496.13
i try all codecs

**Comment by Melonso** [comment] 2021-10-17 09:07
moonlight 1.0.1

**Comment by mariotaku** [comment] 2021-10-17 12:34
@Melonso Could you please check system information in Moonlight Settings - About?
05.10.30 is **not** system version, but firmware version instead.

**Comment by mariotaku** [comment] 2021-10-17 12:54
I see. What's the decoder you're using now?

**Comment by Melonso** [comment] 2021-10-17 13:03
For now its NDL

**Comment by Melonso** [comment] 2021-10-17 13:44
Its the same i trying all codecs

**Comment by mariotaku** [comment] 2021-10-17 13:51
OK. What about the crashes? Do you mean Moonlight quits to your TV channels, or just showing the connection timeout error?

**Comment by Melonso** [comment] 2021-10-17 16:08
IT will be fixed in future versions ? Im asking about moonlight :) for now i make downgrade

**Comment by mariotaku** [comment] 2021-11-07 16:25
How does it work with recent versions? @Melonso

**Comment by Melonso** [comment] 2021-11-17 15:48
I was updating NVIDIA drivers and moonlight to newest version and on 1440p still i have nad connection (5gh wifi) earlier i Has 5-10 ms latency...

**Comment by Melonso** [comment] 2021-11-17 15:57
Little offtop you why applicatcion dissapear from tv after some time ? And still my user is kicked from Dev mode and i need to log in again

**Comment by mariotaku** [comment] 2021-11-17 16:01
> I was updating NVIDIA drivers and moonlight to newest version and on 1440p still i have nad connection (5gh wifi) earlier i Has 5-10 ms latency...

I'm not sure what is the problem. You may need to change your wireless router to a band which doesn't have DFS. (see: https://en.wikipedia.org/wiki/List_of_WLAN_channels)

> Little offtop you why applicatcion dissapear from tv after some time ? And still my user is kicked from Dev mode and i need to log in again

Dev Mode on webOS resets every 50 hours, this is annoying indeed.

**Comment by mariotaku** [comment] 2021-11-17 16:13
With [this tool](https://github.com/webosbrew/dev-manager-desktop) it will be much easier but yes.

**Comment by mariotaku** [comment] 2022-01-19 15:56
Happened few times during gameplay with SMP decoder. Not only the frame stopped, but it seems that the whole video thread was blocked. Needs further investigation and add some error retry/handling.

**Comment by BleskBati** [comment] 2022-01-23 17:20
First time happened today in God of War after about 10 min of playing though i'm using moonlight-tv since ~october.
Video freezed, but sound was good. Workaround - go to Home screen and back again to "Resume Streaming"

@mariotaku, if your application gathers some logs - it would be great to tell where we can get them (may be through webos-dev-manager? add a feature into app to gather logs and save them somewhere to host computer)

My config:
Host - gtx1660, drivers 511.23, 100mb ethernet, but have 1gb ports (don't use wi-fi)
TV - lg 55up77506la, fw 03.21.10, webos 6.2.0, moonlight-tv 1.4.0, streaming 1080p in 25 mbit/sec bitrate (according to settings)

**Comment by adrianolls** [comment] 2022-03-30 15:35
Seems the problem is related with HAGS ( Hardware Accelerated Gpu Scheduling ) and there's nothing to do with moonlight-tv.

to fix this issue and use SMP encoder, just disable HAGS on graphical settings in windows.

after this SMP encoder has been working with 2556x1440 resolution 60 fps for hours without any freeze or stuttering.

**Comment by mariotaku** [comment] 2022-08-27 15:34
Closing this for now. I think this is related to Hardware Accelerated GPU Scheduling.

**Closed by mariotaku** 2022-08-27 15:34 UTC
Labels: bug, video

**Comment by BrenoAquino** [comment] 2023-04-26 14:46
Is there other solution? As HAGS is required for DLSS3 with series 40 it would be nice to have another solution

**Comment by mariotaku** [comment] 2023-04-26 15:26
@BrenoAquino Since it's some issue with HAGS, maybe it's fixed in updates. For other performance issues opening another issue might be a good idea.

**Comment by adrianolls** [comment] 2023-04-26 15:27
> Is there other solution? As HAGS is required for DLSS3 with series 40 it would be nice to have another solution

have you tried sunshine ?
