### ISSUE TITLE
[COMPAT] 65NANO90UNA

### ISSUE THREAD

**Issue by exalented** [mariotaku/moonlight-tv#32] opened 2021-02-10 04:40 UTC
# Basic information

 - Device Model: 65NANO90UNA
 - System Version: 5.2.1-2522
 - Is Audio Working: Yes (SDL Audio)
 - Is Video Working: Yes (webOS is decoding x265/hevc 10bit!)
 - Is Input Working: Yes

# Issues with this particular TV

- [X] Successful 'failed pairing'
- [X] unbinding an unknown host will crash the app
- [X] Backgrounding the app will either crash or error.
- [ ] When navigating the UI the app will sometimes crash.
- [ ] Sometimes launching a game or app will crash the client, but successfully launch it on the server. A workaround for now I've found is to resume a session launched from say an Android client. Seems to work as intended, but your bitrate and resolution are then limited by what you set when you first launched the app.
- [X] client doesn't stay paired/listed after the app is closed (constantly having to retype the ip is quite cumbersome).

**Comment by mariotaku** [comment] 2021-02-10 05:16
Is your computer discoverable? There's no way to pair manually in current version yet.

**Comment by exalented** [comment] 2021-02-10 05:32
The upnp rules are in place. Works from my Android device on the same network.

**Comment by mariotaku** [comment] 2021-02-10 05:37
OK. I'll check it later. I just broke my DevMode so I can't do TV development yet, will make manual pairing available once I'm back.

**Comment by exalented** [comment] 2021-02-11 22:20
Ok I've pushed the 4.3 release to the tv and I can pair and launch games(!), but when I launch a game moonlight-tv will crash out. With the game starting on the GameStream server I punch in my IP address again and press resume on the game which results in another crash. I am currently trying the other decoders.

**Comment by mariotaku** [comment] 2021-02-12 04:28
It seems that you're running latest webOS. Unfortunately current version doesn't run on webOS 5, and I'm still working on reverse engineering for that. I'll keep those similar issues opened until it's working on webOS 5.

**Comment by exalented** [comment] 2021-03-21 05:23
Great news! With the v0.5.2 release this TV is working well enough to stream (I made sure to not update the TV)! Tested with a wired dualshockv1 controller. Didn't experience much latency at all. The gamestream server was running off an EVGA GTX 1080FTWv1 card within a Windows 10 KVM. Amazing work here! All boxes ticked!

**Comment by exalented** [comment] 2021-04-11 04:57
I figured I'd reopen this issue rather than creat another. Few issues with this particular tv (I know some other users have mentioned similar issues):
- Successful 'failed pairing'
- unbinding an unknown host will crash the app
- when navigating the UI with a ps4 remote the app will sometimes crash (it's best to use the magic remote till this is fixed).
- Sometimes I can launch an app from within this client, but sometimes launching a game or app will crash the client, but successfully launch it on the server (a workaround for now I've found is to *resume* a session launched from say an Android client seems to work as intended).
- client doesn't stay paired/listed after the app is closed (constantly having to retype the ip is quite cumbersome).

**Comment by mariotaku** [comment] 2021-04-11 12:56
Status update:

1 - Pairing issue done
2 - Could you please tell me more about this one? What is an unknown host?
3,4 - I'll try on mine and see
5 - Investigating

**Comment by exalented** [comment] 2021-04-11 16:04
When I open the app without pairing to a GameStream server and click the 'i' there's an option to unbind. Instead of showing ip information it says 'unknown host' (it's more of a nitpick than anything, but I thought I'd report it.

**Comment by mariotaku** [comment] 2021-04-11 16:05
Oh great. This is worth fixing indeed. Thanks :)

**Comment by exalented** [comment] 2021-04-11 16:28
Just a small report. v6.3 will not start on this tv.
It just crashes out and kicks you back to whichever app you were viewing.

**Comment by mariotaku** [comment] 2021-04-11 16:43
Can't reproduce yet. Could you execute following command:
```cmd
ares-novacom -r "zcat /tmp/faultmanager/crash/*.gz"
```
And paste all the text here? (I believe it doesn't contain personal information. If you're worry about it, send to my email or via PM on discord)

**Comment by exalented** [comment] 2021-04-11 16:49
Sure. I'll get back to you in a few hours after I get done digging a ditch :P

**Comment by mariotaku** [comment] 2021-04-11 16:54
By the way the SDK doesn't have to be updated as long as it works, if this command doesn't work for you, please let me know.

**Comment by exalented** [comment] 2021-04-12 07:10
Ping to let you know I emailed you and to report that there are no crash logs.

**Comment by exalented** [comment] 2021-04-13 20:04
With v0.6.8 this tv no longer crashes out immediately, but rather audio no longer functions.

**Comment by exalented** [comment] 2021-04-17 15:25
Great job with the 7.0 release. Streaming server stays paired!

**Comment by mariotaku** [comment] 2021-05-01 14:08
Can't reproduce crashes so far. So I'll be closing this issue. For random crashes, please report in separate issue.

**Closed by mariotaku** 2021-05-01 14:08 UTC

**Comment by exalented** [comment] 2021-06-04 19:32
> Can't reproduce crashes so far. So I'll be closing this issue. For random crashes, please report in separate issue.

@mariotaku When using a Sunshine server I found moonlight to no longer crash as described here! The only difference that I notice is that Sunshine doesn't serve images or thumbnails.
