### ISSUE TITLE
Xbox Elite 2 wrong mapping.

### ISSUE THREAD

**Issue by devbpa** [mariotaku/moonlight-tv#190] opened 2022-12-23 00:06 UTC
**Conclusion by developer for wrong gamepad mapping over Bluetooth: There's nothing moonlight can do. [Using an adapter](https://github.com/mariotaku/moonlight-tv/wiki/Gamepad-Setup#webos-tv) should work better.**

---

## Basic information

 - Device model: (    OLED55C1   ) 
 - Firmware version: (       ) 
 - webOS version: (   6.3.1-411    ) 
 - Moonlight version: (   1.5.3    ) 
 - Is audio working: (    Yes   ) 
 - Is video working: (   2k/120fps    ) 
 - Is input working: (    No   ) 

## Description

When I connect my PS4 controller I can play any games, but the system recognize it as a xbox 360 controller, but I can work with that. When I tried to play with my Xbox Elite 2 controller, I couldn't. The TV can pair with the controller, but some commands are completely wrong (such as the left analog).

I can play with that controller on iPad, Apple TV and PC. I just have problems when I try to play with that controller on my LG TV.

**Comment by devbpa** [comment] 2022-12-23 00:13
Also when I connect my Elite 2 to TV using a cable, everything works well

**Comment by mariotaku** [comment] 2022-12-23 10:18
Hi, I think this is because webOS has some buttons incorrectly mapped. And moonlight can't fix this. You may want to use an adapter for that.

**Comment by devbpa** [comment] 2022-12-23 13:01
Which one should I use? I bought an 8BitDo v2, does it work with webOS? If yes, how can I set it up on TV to pair with my controller?

thanks for your support

**Comment by kentyman23** [comment] 2023-01-02 21:52
I think I have the same problem with my Xbox (One) Wireless Controller Gen 2 (Model 1708) on my LG C2 when connected via Bluetooth. Games think I have a gamepad connected, but the mapping seems all wrong. Any hope for using this controller?

**Comment by kentyman23** [comment] 2023-01-03 01:26
Actually, I found a solution for my problem. I confirmed that the controller also had bad mappings in the native GeForce Now app. Reverting the controller firmware fixed it.

You can do it by following these instructions: https://support.xbox.com/en-US/help/hardware-network/accessories/controller-firmware-reversion (note that even from the Xbox, you have to expand the PC section to get to "Check you controller's firmware" to be able to revert).

I speculate that it broke when they changed to BLE (Low Energy) with the following update. Sadly, it means we don't get the double-tap switch between Xbox and Bluetooth after the revert: https://www.theverge.com/2021/9/8/22663039/microsoft-xbox-controller-firmware-dynamic-latency-input-dli-bluetooth-low-energy

**Comment by kentyman23** [comment] 2023-01-03 15:49
Anyone know any way to force the controller to behave one way instead of the other like mentioned in these 2 posts?
https://www.reddit.com/r/xboxinsiders/comments/r0d9zz/xbox_one_s_controller_no_longer_works_as_it/
https://www.reddit.com/r/xboxinsiders/comments/qeagsm/comment/hk1yk6b/?utm_source=share&utm_medium=web2x&context=3

@BrenoAquino, is it easy to pick which adapter (8bitDo instead of built-in) you're pairing with? How does that work?

**Comment by BrenoAquino** [comment] 2023-01-03 16:02
@kentyman23  I have the USB v2 wireless adapter (https://www.8bitdo.com/wireless-usb-adapter-2/). It was very easy to set it up. I tested it on my Windows PC and two LG TVs. They all worked great.

You just need to plug in your PC, update the firmware, and to pair, just press the adapter button and put the controller in pairing mode (you can do this anywhere, you just need to power the adapter).

To work on webOS I needed to change the mode to Dinput mode. To do this, after pairing, you need to hold VIEW + LEFT in the controller and done. To understand a little more about it, you can see it here: https://support.8bitdo.com/Manual/USB-Adapter-2/xbox-windows.html

But I really recommend this adapter with the xbox controller (I use the elite 2 controller). It's really reliable and you can just unplug and plug anywhere because I will connect to your controller automatically

**Comment by kentyman23** [comment] 2023-01-20 00:01
By the way, I don't think it's actually because of Bluetooth Low Energy, as I just [updated](https://stadia.google.com/controller/) my old Stadia controller to use Bluetooth LE instead of Wi-Fi and it works great with GeForce Now. However, I can't seem to get it to do anything in Moonlight on my LG C2. Maybe this needs a new issue?

**Comment by mariotaku** [comment] 2023-06-20 16:58
Closing as webOS gamepad support over Bluetooth can't be fixed on moonlight's side.

**Closed** 2023-06-20 16:57 UTC
Labels: compatibility, input
