### ISSUE TITLE
[BUG] Moonlight on WebOSTV V4.9 - crash on every single instance

### ISSUE THREAD

**Issue by ozankaruk** [mariotaku/moonlight-tv#214] opened 2023-03-11 12:01 UTC
*Describe the bug*

Moonlight always crashes when trying to stream the game on WebOSTV V4.9

*To Reproduce*

Open the Moonlight client.
Choose the game to run & stream on your host (win11 PC)
Moonlight shuts down and screen returns to TV mode.

*Expected behavior*

Moonlight had to stream the game to the TV without any issues.

*Basic information*

 - Moonlight version: 1.5.3_arm.ipk - LG WebOSTV
 - Model: LG 65um7100pla - 4k TV
 - webOS version : 4.9 - firmware : 05.30.30]

I've recently finished setting up Moonlight for a Led 4K TV which runs on LG WebOStv 4.9 I have an RTX 2060 PC which runs on windows 11. Both are connected through a 5Ghz wi-fi network in the same house.

However, I couldn't get even a single second of a stream. I don't know what the problem might be. I've made the additions to GFE Shield games .exe list. My TV recognize the game, my pc runs the game, but when I try to play it from the TV, Moonlight crashes and TV returns back to its standart TV mode. I use another third party WebOS app to connect my Xbox one gamepads through bluetooth to the TV -which seem to be working fine. I don't know if those could be the reason behind this issue.

Another thing that I noticed is the streaming protocols of my TV looks like not supporting h265 streaming standart. However, I can't change h265 streaming option, it's unclickable. This would be my guess, but what do I know anyways...

BTW: Yes, I disabled HAGS.

Is there anybody who can help? I'm pretty new in moonlight and I don't know a single bit of software coding. I'd really appreciate if anyone could provide any assitance.

**Comment by mariotaku** [comment] 2023-03-13 02:56
Hi. The issue is on the TV side so no need to change PC settings. Can you try switch the audio backend to ALSA or PulseAudio?

**Comment by ozankaruk** [comment] 2023-03-14 10:14
> Hi. The issue is on the TV side so no need to change PC settings. Can you try switch the audio backend to ALSA or PulseAudio?

Worked like a charm. Tried ALSA first. Video was fine but the audio was really stuttering, laggy, distorted and high pitched. Converted to PulseAudio and VOILA!

Another problem emerged, tho. But I'll not ask it under this thread.

Thanks for the advice. Case is closed. :)

**Comment by mariotaku** [comment] 2023-05-24 16:15
On latest release, crashes related to audio backend has been fixed. So officially closing this.

**Closed by mariotaku** 2023-05-24 16:15 UTC
