### ISSUE TITLE
[BUG] Crash upon bringing up the virtual keyboard before adding a server

### ISSUE THREAD

**Issue by exalented** [mariotaku/moonlight-tv#74] opened 2021-06-07 23:56 UTC
**Describe the bug**
Client crashes while adding server right as the keyboard starts to show up.
**To Reproduce**
1. Launch Moonlight
2. Click on the plus button at the top right of the screen somewhat **_quickly_**
3. Experience crash

**Expected behavior**
No crashes should occur.

**LG webOS TV:**
 - Model: 65NANO90UNA
 - webOS version: 5.2.1
 - software version: 03.21.80

**Additional context**
This seems to happen more frequently when you check your server list and then try to add a server **_quickly_**. To mitigate this, after opening the app wait just a few moments and then try adding your server. #72 might be related, but this also happens with Nvidia Experience on windows.
v0.4.4 gzip'd logs 
[4.4.log](https://github.com/mariotaku/moonlight-tv/files/6895269/4.4.log)
v0.7.11 gzip'd logs
[addservercrash.log](https://github.com/mariotaku/moonlight-tv/files/6612539/addservercrash.log)
v0.7.11 logs in `/tmp`
[addservercrash2.log](https://github.com/mariotaku/moonlight-tv/files/6618579/addservercrash2.log)
v0.7.12 logs in `/tmp`
[addservercrash_7.12.log](https://github.com/mariotaku/moonlight-tv/files/6618679/addservercrash_7.12.log)
v0.9.0 gzip'd logs 
[0.9.0.log](https://github.com/mariotaku/moonlight-tv/files/6895398/0.9.0.log)
v0.9.2 gzip'd logs
[v0.9.2.log](https://github.com/mariotaku/moonlight-tv/files/6909396/v0.9.2.log)
v0.9.3 gzip'd logs
[v0.9.3.log](https://github.com/mariotaku/moonlight-tv/files/6910402/v0.9.3.log)
v0.9.90 gzip'd logs
[v0.9.90.log](https://github.com/mariotaku/moonlight-tv/files/7248121/crashLog_v0.9.90.log)

**Comment by mariotaku** [comment] 2021-06-08 02:27
Not sure why but those logs are truncated. I'll try to reproduce first.

**Comment by exalented** [comment] 2021-06-08 17:40
The previous log was zcated from another location. I had a look at another issue and they cated a log from `/tmp`, so here's that log https://github.com/mariotaku/moonlight-tv/files/6618579/addservercrash2.log

**Comment by KeepSummerSaf3** [comment] 2021-07-23 04:52
Maybe a related issue. In this case I am attempting to add a host, the window to enter the host IP is available; however, as soon as it is selected with the pointer the app will crash. Note, I am using a "virtual magic remote" (phone app) as the physical remote only has a dpad.
[moonlight.log](https://github.com/mariotaku/moonlight-tv/files/6866649/moonlight.log)

**Comment by exalented** [comment] 2021-07-30 18:53
Also note that the app won't crash if you only open the add server dialogue. You have to select the input field to type in an ip for it to crash.

**Comment by mariotaku** [comment] 2021-09-28 16:31
Maybe it's some bug inside SDL shipped with webOS, but I did some major UI change, what about now?

**Comment by KeepSummerSaf3** [comment] 2021-09-28 16:36
Awesome! While I may not have the same issue (or it may be different since I am using a virtual magic remote) I will retry today and report back.

**Comment by exalented** [comment] 2021-09-29 00:32
I am unable to reproduce this across many versions of moonlight-tv after a WebOS update to v5.2.3-252111.

**Comment by mariotaku** [comment] 2021-09-29 02:28
Great. I'll close this for now.

**Closed by mariotaku** 2021-09-29 02:28 UTC
Labels: bug

**Comment by KeepSummerSaf3** [comment] 2021-09-29 03:09
Realize this is closed, but I can also confirm 0.9.92 works with the virtual magic remote. direct input through the app or virtual keyboard works without crashing the application. Minor issue with selecting and holding focus for the virtual keyboard; workaround is to close and re-open the window.
